name: Deploy

on:
  push:
    branches: [ main ]

jobs: 
  build:

     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
         with:
           node-version: 12
       - run: npm install -g 
       - run: npm install --frozen-lockfile
       - run: npm build
       - uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secret.AWS_ACCESS_KEY_ID }}
           aws-region: us-east-1
